plugins {
    id 'java'
}

group = 'com.friendaliases'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.runelite.net' }
}

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: '1.12.38'
    testImplementation 'junit:junit:4.13.2'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
